name: "${project.name}"
main: no.atc.floyd.bukkit.ban.BanPlugin
version: "${project.version}"
website: "${project.url}"
author: FloydATC
description: "${project.description}"

commands:
  bp:
    description: Ban Plugin internal commands
    usage: /<command> reload
    permission: BanPlugin.bp
  permban:
    description: Ban named player permanently
    usage: /<command> <player> <reason>
    permission: BanPlugin.permban
  tempban:
    description: Ban named player temporarily
    usage: /<command> <player> <duration> <reason>
    permission: BanPlugin.tempban
  unban:
    description: Unban named player
    usage: /<command> <player> <reason>
    permission: BanPlugin.unban
  checkban:
    description: Check if named player is banned
    usage: /<command> <player>
    permission: BanPlugin.checkban
  kick:
    description: Kick player off server, with optional reason
    usage: /<command> player [reason] - Kick a player
    permission: BanPlugin.kick
  warn:
    description: Issue warning to player, with optional reason
    usage: /<command> <player> [<reason>]
    permission: BanPlugin.warn
